var myObject = {
    "hiHelloMonster": [{
        "img-src": "hhm.png",
        "fecha-De-Publicacion": "20 de junio 2021",
        "a-href": "https://hihello.monster/how-to/css-image-modal.html",
        "a-href-tittle": "Tab-Pure-CSS",
        "el-Post": "Debo llevar más control sobre cada formato. Tengo que si el de Xiiber, que si el de Marthech, que si el personal. <br>En general fue un día pesado pero con buenos resultados.<br><br> <strong>El mode multicolor </strong> quedo ok, <b>el scroll, listo</b>, pero se reptio el templete de <i>viajes</i>. Estuve aprendiendo a sacarle provecho al Studio. Le pude poner link a una imagen. La lección más importante del día es... <br><br>hazlo y no busques templetes, más recisa bien los apuntes o instrucciones de la W3 y/o Mozilla. Todo por no hacer eso, he tenido que trabajar al doble y perder tiempo extra buscando. Que esta bien, pero ya demore mucho. <br><br>El mismo día hice dos versiones, una con una base URL y la segunda solo utilizando exclusivamente el W3.JS. Hice el primer example dedicado a la misma herramienta que me esta encantado",
        "accion": "Ver",
        "postFoto1": "https://www.xiiber.com/img/photo-preview-01.png",
        "altPostFoto1": "Alt Post Foto 1",
        "postFoto2": "https://www.xiiber.com/img/photo-preview-02.png",
        "altPostFoto2": "Alt Post Foto 2",
        "postFoto3": "https://www.xiiber.com/img/photo-preview-03.png",
        "altPostFoto3": "Alt Post Foto 3",
        "postFoto4": "https://www.xiiber.com/img/photo-preview-00.png",
        "altPostFoto4": "Alt Post Foto 4",
    }, {
        "img-src": "hhm.png",
        "fecha-De-Publicacion": "19 de junio 2021",
        "a-href": "https://hihello.monster/how-to/css-image-modal.html",
        "a-href-tittle": "Tab-Pure-CSS",
        "el-Post": "Para crear esta primera instancia, utilice w3.js como base para programar. Referente al diseño, el style se integro en cada instruccion, esto opr que w3.js jala con todo su style al proyecto principal. <br><br> La base de datos esta integrada en el mismo archivo que tambien incluye una instrución para personalizar las URL y estas puedan ayudar a generar más rapido un Mapa de sitios y enlaces de información por entrada en el sitio. <br><br>  <b>Quede muy contento con el resultado </b>y la lección de este día fue: guardar una copia de los js y css para no sufrir como sufri.Resulta que la pagina de la w3 no estaba linea!!!!!cuando estaba corriendo la penultima prueba, jalaba todo super bien, le hice un ajuste y zas,   cuando vuelvo actualizar resulta que el.js salia con errores por que no encontraba el servidor. <br><br> Me paso por la cabeza mil cosas, valide la información en una pagina, dos paginas, un navegador, en el celular y hasta  reinicie la computadora. <br>  <br> Pero ya quedo la lección aprendida",
        "accion": "Ver ",
        "postFoto1": "https://www.xiiber.com/img/photo-preview-01.png",
        "altPostFoto1": "Alt Post Foto 1",
        "postFoto2": "https://www.xiiber.com/img/photo-preview-02.png",
        "altPostFoto2": "Alt Post Foto 2",
        "postFoto3": "https://www.xiiber.com/img/photo-preview-03.png",
        "altPostFoto3": "Alt Post Foto 3",
        "postFoto4": "https://www.xiiber.com/img/photo-preview-00.png",
        "altPostFoto4": "Alt Post Foto 4",
    }, {
        "img-src": "hhm.png",
        "fecha-De-Publicacion": "14-agosto-2021",
        "a-href": "https://hihello.monster/how-to/Tab-Pure-CSS/ ",
        "a-href-tittle": "Tab-Pure-CSS",
        "how-to-tittle": "Tab-Pure-CSS",
        "el-Post": "Tab-Pure-CSS",
        "accion": "Descargar",
        "postFoto1": "https://www.xiiber.com/img/photo-preview-01.png",
        "altPostFoto1": "Alt Post Foto 1",
        "postFoto2": "https://www.xiiber.com/img/photo-preview-02.png",
        "altPostFoto2": "Alt Post Foto 2",
        "postFoto3": "https://www.xiiber.com/img/photo-preview-03.png",
        "altPostFoto3": "Alt Post Foto 3",
        "postFoto4": "https://www.xiiber.com/img/photo-preview-00.png",
        "altPostFoto4": "Alt Post Foto 4",
    }, {
        "img-src": "hhm.png",
        "fecha-De-Publicacion": "14-agosto-2021",
        "a-href": "https://hihello.monster/how-to/Tab-Pure-CSS/ ",
        "a-href-tittle": "Tab-Pure-CSS",
        "how-to-tittle": "Tab-Pure-CSS",
        "el-Post": "Tab-Pure-CSS",
        "accion": "Descargar",
        "postFoto1": "https://www.xiiber.com/img/photo-preview-01.png",
        "altPostFoto1": "Alt Post Foto 1",
        "postFoto2": "https://www.xiiber.com/img/photo-preview-02.png",
        "altPostFoto2": "Alt Post Foto 2",
        "postFoto3": "https://www.xiiber.com/img/photo-preview-03.png",
        "altPostFoto3": "Alt Post Foto 3",
        "postFoto4": "https://www.xiiber.com/img/photo-preview-00.png",
        "altPostFoto4": "Alt Post Foto 4",

    }, {
        "img-src": "hhm.png",
        "fecha-De-Publicacion": "16-agosto-2021",
        "a-href": "https://hihello.monster/how-to/responsive-typography-generator/",
        "a-href-tittle": "Tab-Pure-CSS",
        "how-to-tittle": "Responsive-typography-generator",
        "el-Post": "Hice tal cosa",
        "accion": "Descargar",
        "postFoto1": "",
        "altPostFoto1": "",
        "postFoto2": "",
        "altPostFoto2": "",
        "postFoto3": "",
        "altPostFoto3": "",
        "postFoto4": "",
        "altPostFoto4": "",
    }, {
        "img-src": "hhm.png",
        "fecha-De-Publicacion": "16-agosto-2021",
        "a-href": "https://hihello.monster/how-to/simple-blog-concept-pure-modal-tab-icon-efect-css/",
        "a-href-tittle": "Tab-Pure-CSS",
        "how-to-tittle": "Simple-blog-concept-pure-modal-tab-icon-efect-css",
        "el-Post": "Hice tal cosa",
        "accion": "Descargar",
        "postFoto1": "",
        "altPostFoto1": "",
        "postFoto2": "",
        "altPostFoto2": "",
        "postFoto3": "",
        "altPostFoto3": "",
        "postFoto4": "",
        "altPostFoto4": "",
    }, {
        "img-src": "hhm.png",
        "fecha-De-Publicacion": "16-agosto-2021",
        "a-href": "https://hihello.monster/how-to/DateTime.html ",
        "a-href-tittle": "Tab-Pure-CSS",
        "how-to-tittle": "DateTime",
        "el-Post": "Hice tal cosa",
        "accion": "Descargar",
        "postFoto1": "https://www.xiiber.com/img/photo-preview-01.png",
        "altPostFoto1": "Alt Post Foto 1",
        "postFoto2": "https://www.xiiber.com/img/photo-preview-02.png",
        "altPostFoto2": "Alt Post Foto 2",
        "postFoto3": "https://www.xiiber.com/img/photo-preview-03.png",
        "altPostFoto3": "Alt Post Foto 3",
        "postFoto4": "https://www.xiiber.com/img/photo-preview-00.png",
        "altPostFoto4": "Alt Post Foto 4",
    }, {
        "img-src": "hhm.png",
        "fecha-De-Publicacion": "16-agosto-2021",
        "a-href": "https://hihello.monster/how-to/Expanding-Menu-Concept.html",
        "a-href-tittle": "Tab-Pure-CSS",
        "how-to-tittle": "Expanding-Menu-Concept.",
        "el-Post": "Hice tal cosa",
        "accion": "Descargar",
        "postFoto1": "https://www.xiiber.com/img/photo-preview-01.png",
        "altPostFoto1": "Alt Post Foto 1",
        "postFoto2": "https://www.xiiber.com/img/photo-preview-02.png",
        "altPostFoto2": "Alt Post Foto 2",
        "postFoto3": "https://www.xiiber.com/img/photo-preview-03.png",
        "altPostFoto3": "Alt Post Foto 3",
        "postFoto4": "https://www.xiiber.com/img/photo-preview-00.png",
        "altPostFoto4": "Alt Post Foto 4",
    }, {
        "img-src": "hhm.png",
        "fecha-De-Publicacion": "15-agosto-2021",
        "a-href": "https://hihello.monster/how-to/Lightbox+Horizontal_Scrollable_menu.html",
        "a-href-tittle": "Tab-Pure-CSS",
        "how-to-tittle": "Lightbox+Horizontal_Scrollable_menu",
        "el-Post": "Hice tal cosa",
        "accion": "Descargar",
        "postFoto1": "https://www.xiiber.com/img/photo-preview-01.png",
        "altPostFoto1": "Alt Post Foto 1",
        "postFoto2": "https://www.xiiber.com/img/photo-preview-02.png",
        "altPostFoto2": "Alt Post Foto 2",
        "postFoto3": "https://www.xiiber.com/img/photo-preview-03.png",
        "altPostFoto3": "Alt Post Foto 3",
        "postFoto4": "https://www.xiiber.com/img/photo-preview-00.png",
        "altPostFoto4": "Alt Post Foto 4",
    }, {
        "img-src": "hhm.png",
        "fecha-De-Publicacion": "16-agosto-2021",
        "a-href": "https://hihello.monster/how-to/modal-CSS.html",
        "a-href-tittle": "Tab-Pure-CSS",
        "how-to-tittle": "Modal-CSS",
        "el-Post": "Hice tal cosa",
        "accion": "Descargar",
        "postFoto1": "https://www.xiiber.com/img/photo-preview-01.png",
        "altPostFoto1": "Alt Post Foto 1",
        "postFoto2": "https://www.xiiber.com/img/photo-preview-02.png",
        "altPostFoto2": "Alt Post Foto 2",
        "postFoto3": "https://www.xiiber.com/img/photo-preview-03.png",
        "altPostFoto3": "Alt Post Foto 3",
        "postFoto4": "https://www.xiiber.com/img/photo-preview-00.png",
        "altPostFoto4": "Alt Post Foto 4",
    }, {
        "img-src": "hhm.png",
        "fecha-De-Publicacion": "16-agosto-2021",
        "a-href": "https://hihello.monster/how-to/simpleModal.html",
        "a-href-tittle": "Tab-Pure-CSS",
        "how-to-tittle": "Simple Modal",
        "el-Post": "Hice tal cosa",
        "accion": "Descargar",
        "postFoto1": "https://www.xiiber.com/img/photo-preview-01.png",
        "altPostFoto1": "Alt Post Foto 1",
        "postFoto2": "https://www.xiiber.com/img/photo-preview-02.png",
        "altPostFoto2": "Alt Post Foto 2",
        "postFoto3": "https://www.xiiber.com/img/photo-preview-03.png",
        "altPostFoto3": "Alt Post Foto 3",
        "postFoto4": "https://www.xiiber.com/img/photo-preview-00.png",
        "altPostFoto4": "Alt Post Foto 4",
    }, {
        "img-src": "hhm.png",
        "fecha-De-Publicacion": "5-julio-2021",
        "a-href": "https://hihello.monster/how-to/i/style.css",
        "a-href-tittle": "Iconos para ilustrar los ejemplos How-to",
        "how-to-tittle": "https://hihello.monster/how-to/i/style.css",
        "el-Post": "Iconos para ilustrar los ejemplos How-to. Si te gustan, son tuyos. Los puedes descargar",
        "accion": "Ver todos los iconos",
        "postFoto1": "https://www.xiiber.com/img/photo-preview-01.png",
        "altPostFoto1": "Alt Post Foto 1",
        "postFoto2": "https://www.xiiber.com/img/photo-preview-02.png",
        "altPostFoto2": "Alt Post Foto 2",
        "postFoto3": "https://www.xiiber.com/img/photo-preview-03.png",
        "altPostFoto3": "Alt Post Foto 3",
        "postFoto4": "https://www.xiiber.com/img/photo-preview-00.png",
        "altPostFoto4": "Alt Post Foto 4",
    }, {
        "img-src": "hhm.png",
        "fecha-De-Publicacion": "8 de julio",
        "a-href": "https: //hihello.monster/how-to/mapa-de-sitio.html",
        "a-href-tittle": "Mapa de sitio",
        "how-to-tittle": "Mapa de sitio",
        "el-Post": "apa de sitio ejemplo Xiiber",
        "accion": "Ver",
        "postFoto1": "https://www.xiiber.com/img/photo-preview-01.png",
        "altPostFoto1": "Alt Post Foto 1",
        "postFoto2": "https://www.xiiber.com/img/photo-preview-02.png",
        "altPostFoto2": "Alt Post Foto 2",
        "postFoto3": "https://www.xiiber.com/img/photo-preview-03.png",
        "altPostFoto3": "Alt Post Foto 3",
        "postFoto4": "https://www.xiiber.com/img/photo-preview-00.png",
        "altPostFoto4": "Alt Post Foto 4",
    }, {
        "img-src": "hhm.png",
        "fecha-De-Publicacion": "8 julio 2021",
        "a-href": "https: //hihello.monster/how-to/cambio_de_texto.html",
        "a-href-tittle": "Cambio de texto",
        "how-to-tittle": "Cambio de texto",
        "el-Post": "Cambio de texto",
        "accion": "Descargar",
        "postFoto1": "https://www.xiiber.com/img/photo-preview-01.png",
        "altPostFoto1": "Alt Post Foto 1",
        "postFoto2": "https://www.xiiber.com/img/photo-preview-02.png",
        "altPostFoto2": "Alt Post Foto 2",
        "postFoto3": "https://www.xiiber.com/img/photo-preview-03.png",
        "altPostFoto3": "Alt Post Foto 3",
        "postFoto4": "https://www.xiiber.com/img/photo-preview-00.png",
        "altPostFoto4": "Alt Post Foto 4",
    }, {
        "img-src": "hhm.png",
        "fecha-De-Publicacion": "9 julio 2021",
        "a-href": "https://hihello.monster/how-to/tab-in-tab.html",
        "a-href-tittle": "Tab-Pure-CSS",
        "how-to-tittle": "Tab in tab",
        "el-Post": "Tab in tab",
        "accion": "Ver ejemplo",
        "postFoto1": "https://www.xiiber.com/img/photo-preview-01.png",
        "altPostFoto1": "Alt Post Foto 1",
        "postFoto2": "https://www.xiiber.com/img/photo-preview-02.png",
        "altPostFoto2": "Alt Post Foto 2",
        "postFoto3": "https://www.xiiber.com/img/photo-preview-03.png",
        "altPostFoto3": "Alt Post Foto 3",
        "postFoto4": "https://www.xiiber.com/img/photo-preview-00.png",
        "altPostFoto4": "Alt Post Foto 4",
    }, {
        "img-src": "hhm.png",
        "fecha-De-Publicacion": "10 julio 2021",
        "a-href": "https://hihello.monster/how-to/popup-window-opener-location-href-document-location",
        "a-href-tittle": "Popup-window-opener-location-href-document-location",
        "how-to-tittle": "popup-window-opener-location-href-document-location",
        "el-Post": "Popup-window-opener-location-href-document-location",
        "accion": "Descargar",
        "postFoto1": "https://www.xiiber.com/img/photo-preview-01.png",
        "altPostFoto1": "Alt Post Foto 1",
        "postFoto2": "https://www.xiiber.com/img/photo-preview-02.png",
        "altPostFoto2": "Alt Post Foto 2",
        "postFoto3": "https://www.xiiber.com/img/photo-preview-03.png",
        "altPostFoto3": "Alt Post Foto 3",
        "postFoto4": "https://www.xiiber.com/img/photo-preview-00.png",
        "altPostFoto4": "Alt Post Foto 4",
    }, {
        "img-src": "hhm.png",
        "fecha-De-Publicacion": "8 julio 2021",
        "a-href": "https://hihello.monster/how-to/twitter-follow-boton-door ",
        "a-href-tittle": "twitter-follow-boton",
        "how-to-tittle": "Twitter-follow-boton",
        "el-Post": "Follow me - Twitter boton abre y cierra tipo puerta",
        "accion": "Descargar",
        "postFoto1": "",
        "altPostFoto1": "",
        "postFoto2": "",
        "altPostFoto2": "",
        "postFoto3": "",
        "altPostFoto3": "",
        "postFoto4": "",
        "altPostFoto4": "",
    }, {
        "img-src": "hhm.png",
        "fecha-De-Publicacion": "9 julio 2021",
        "a-href": "https://hihello.monster/how-to/twitter-follow-boton-de-colors",
        "a-href-tittle": "Twitter Follow boton de colores",
        "how-to-tittle": "Twitter follow boton de colores con solo poner el puntero sobre la imagen",
        "el-Post": "El icono de Twitter cambia de colores y lleva directo al perfil con la opción de <i>seguir</i> al usuario",
        "accion": "Copialo",
        "postFoto1": "",
        "altPostFoto1": "",
        "postFoto2": "",
        "altPostFoto2": "",
        "postFoto3": "",
        "altPostFoto3": "",
        "postFoto4": "",
        "altPostFoto4": "",
    }, , {
        "img-src": "hhm.png",
        "fecha-De-Publicacion": "9 julio 2021",
        "a-href": "https://hihello.monster/how-to/twitter-follow-boton-logo.html",
        "a-href-tittle": "Twitter Follow boton de colores",
        "how-to-tittle": "Twitter follow boton de colores con solo poner el puntero sobre la imagen",
        "el-Post": "El icono de Twitter se dezliza",
        "accion": "Copialo",
        "postFoto1": "",
        "altPostFoto1": "",
        "postFoto2": "",
        "altPostFoto2": "",
        "postFoto3": "",
        "altPostFoto3": "",
        "postFoto4": "",
        "altPostFoto4": "",
    }, {
        "img-src": "hhm.png",
        "fecha-De-Publicacion": "Star-wars-himno-nacional-mexicano",
        "a-href": "https://hihello.monster/how-to/star-wars-himno-nacional-mexicano",
        "a-href-tittle": "Starwars-himno-nacional-mexicano",
        "how-to-tittle": "El himno Nacional Mexicano con fecto del intro de Starwars ",
        "el-Post": "El himno Nacional Mexicano con fecto del intro de Starwars",
        "accion": "Ver ahora",
        "postFoto1": "",
        "altPostFoto1": "",
        "postFoto2": "",
        "altPostFoto2": "",
        "postFoto3": "",
        "altPostFoto3": "",
        "postFoto4": "",
        "altPostFoto4": "",
    }, {
        "img-src": "hhm.png",
        "fecha-De-Publicacion": "",
        "a-href": "https://hihello.monster/how-to/bio",
        "a-href-tittle": "Encabezado de un perfil de social media",
        "how-to-tittle": "Encabezado de un perfil de social media",
        "el-Post": "Encabezado de un perfil de social media",
        "accion": "Ver",
        "postFoto1": "",
        "altPostFoto1": "",
        "postFoto2": "",
        "altPostFoto2": "",
        "postFoto3": "",
        "altPostFoto3": "",
        "postFoto4": "",
        "altPostFoto4": "",
    }, {
        "img-src": "hhm.png",
        "fecha-De-Publicacion": "",
        "a-href": "https://hihello.monster/how-to/ficha-de-producto.html",
        "a-href-tittle": "ficha-de-producto.html",
        "how-to-tittle": "ficha-de-producto.html",
        "el-Post": "ficha-de-producto.html",
        "accion": "Descargar Ficha de producto",
        "postFoto1": "",
        "altPostFoto1": "",
        "postFoto2": "",
        "altPostFoto2": "",
        "postFoto3": "",
        "altPostFoto3": "",
        "postFoto4": "",
        "altPostFoto4": "",
    }, {
        "img-src": "hhm.png",
        "fecha-De-Publicacion": "9 julio 2021",
        "a-href": "https://hihello.monster/how-to/loader-travel/",
        "a-href-tittle": "Loader Travel",
        "how-to-tittle": "Loader Travel",
        "el-Post": "Loader animado para CG Travel",
        "accion": "Ver",
        "postFoto1": "",
        "altPostFoto1": "",
        "postFoto2": "",
        "altPostFoto2": "",
        "postFoto3": "",
        "altPostFoto3": "",
        "postFoto4": "",
        "altPostFoto4": "",
    }, {
        "img-src": "xiiber.png",
        "fecha-De-Publicacion": "",
        "a-href": "https://xiiberpage.github.io/cgtravel/",
        "a-href-tittle": "Linktr.ee",
        "how-to-tittle": "Linktr.ee",
        "el-Post": "Linktr.ee de CG Travel",
        "accion": "Ver",
        "postFoto1": "",
        "altPostFoto1": "",
        "postFoto2": "",
        "altPostFoto2": "",
        "postFoto3": "",
        "altPostFoto3": "",
        "postFoto4": "",
        "altPostFoto4": "",
    }, {
        "img-src": "dragvesti.png",
        "fecha-De-Publicacion": "8 julio 2021",
        "a-href": "https://hihellomonster.github.io/dragvesti/Linktr.ee",
        "a-href-tittle": "Linktr.ee Dragvesti",
        "how-to-tittle": "Linktr.ee Dragvesti",
        "el-Post": "Redes sociales de Dragvesti, La Carrera drag Queen",
        "accion": "Ver",
        "postFoto1": "",
        "altPostFoto1": "",
        "postFoto2": "",
        "altPostFoto2": "",
        "postFoto3": "",
        "altPostFoto3": "",
        "postFoto4": "",
        "altPostFoto4": "",
    }, {
        "img-src": "hhm.png",
        "fecha-De-Publicacion": "",
        "a-href": "https://hihello.monster/quiz",
        "a-href-tittle": "ficha-de-producto.html",
        "how-to-tittle": "ficha-de-producto.html",
        "el-Post": "Quiz",
        "accion": "Descargar Ficha de producto",
        "postFoto1": "",
        "altPostFoto1": "",
        "postFoto2": "",
        "altPostFoto2": "",
        "postFoto3": "",
        "altPostFoto3": "",
        "postFoto4": "",
        "altPostFoto4": "",
    }, {
        "img-src": "dragvesti.png",
        "fecha-De-Publicacion": "9 julio 2021",
        "a-href": "https://hihello.monster/how-to/loader-travel/",
        "a-href-tittle": "Linktr.ee Dragvesti",
        "how-to-tittle": "Linktr.ee Dragvesti",
        "el-Post": "Redes sociales de Dragvesti, La Carrera drag Queen",
        "accion": "Ver",
        "postFoto1": "",
        "altPostFoto1": "",
        "postFoto2": "",
        "altPostFoto2": "",
        "postFoto3": "",
        "altPostFoto3": "",
        "postFoto4": "",
        "altPostFoto4": "",
    }, {
        "img-src": "dragvesti.png",
        "fecha-De-Publicacion": "9 julio 2021",
        "a-href": "https://hihello.monster/how-to/descuento/ ",
        "a-href-tittle": "Descuento",
        "how-to-tittle": "Descuento",
        "el-Post": "Descuento",
        "accion": "Ver",
        "postFoto1": "",
        "altPostFoto1": "",
        "postFoto2": "",
        "altPostFoto2": "",
        "postFoto3": "",
        "altPostFoto3": "",
        "postFoto4": "",
        "altPostFoto4": "",
    }, {
        "img-src": "dragvesti.png",
        "fecha-De-Publicacion": "9 julio 2021",
        "a-href": "https://hihello.monster/how-to/boton-modal-flotante.html",
        "a-href-tittle": "Descuento",
        "how-to-tittle": "Descuento",
        "el-Post": "Boton-modal-flotante",
        "accion": "Ver",
        "postFoto1": "",
        "altPostFoto1": "",
        "postFoto2": "",
        "altPostFoto2": "",
        "postFoto3": "",
        "altPostFoto3": "",
        "postFoto4": "",
        "altPostFoto4": "",
    }, {
        "img-src": "dragvesti.png",
        "fecha-De-Publicacion": "9 julio 2021",
        "a-href": "https://hihello.monster/envialov",
        "a-href-tittle": "Envialov",
        "how-to-tittle": "Envialov",
        "el-Post": "Envialov",
        "accion": "Ver",
        "postFoto1": "",
        "altPostFoto1": "",
        "postFoto2": "",
        "altPostFoto2": "",
        "postFoto3": "",
        "altPostFoto3": "",
        "postFoto4": "",
        "altPostFoto4": "",
    }, {
        "img-src": "dragvesti.png",
        "fecha-De-Publicacion": "9 julio 2021",
        "a-href": "https://hihello.monster/how-to/code-tab-in-tab.html",
        "a-href-tittle": "code-tab-in-tab",
        "how-to-tittle": "code-tab-in-tab",
        "el-Post": "code-tab-in-tab",
        "accion": "Ver",
        "postFoto1": "",
        "altPostFoto1": "",
        "postFoto2": "",
        "altPostFoto2": "",
        "postFoto3": "",
        "altPostFoto3": "",
        "postFoto4": "",
        "altPostFoto4": "",
    }, {
        "img-src": "dragvesti.png",
        "fecha-De-Publicacion": "9 julio 2021",
        "a-href": "https://hihello.monster/how-to/hamburguesas.html",
        "a-href-tittle": "",
        "how-to-tittle": "",
        "el-Post": "hamburguesas.html",
        "accion": "Ver",
    }, {
        "postFoto1": "",
        "altPostFoto1": "",
        "postFoto2": "",
        "altPostFoto2": "",
        "postFoto3": "",
        "altPostFoto3": "",
        "postFoto4": "",
        "altPostFoto4": "",
        "img-src": "dragvesti.png",
        "fecha-De-Publicacion": "9 julio 2021",
        "a-href": "https://hihello.monster/how-to/cat",
        "a-href-tittle": "",
        "how-to-tittle": "",
        "el-Post": "¿Y el lindo gatito?",
        "accion": "Ver",
        "postFoto1": "",
        "altPostFoto1": "",
        "postFoto2": "",
        "altPostFoto2": "",
        "postFoto3": "",
        "altPostFoto3": "",
        "postFoto4": "",
        "altPostFoto4": "",
    }, {
        "img-src": "dragvesti.png",
        "fecha-De-Publicacion": "9 julio 2021",
        "a-href": "https://hihello.monster/how-to/ScrollDownHorizontalScrollableMenu.html",
        "a-href-tittle": "",
        "how-to-tittle": "",
        "el-Post": "ScrollDownHorizontalScrollableMenu.html",
        "accion": "Ver",
        "postFoto1": "",
        "altPostFoto1": "",
        "postFoto2": "",
        "altPostFoto2": "",
        "postFoto3": "",
        "altPostFoto3": "",
        "postFoto4": "",
        "altPostFoto4": "",
    }, {
        "img-src": "dragvesti.png",
        "fecha-De-Publicacion": "9 julio 2021",
        "a-href": "https://hihello.monster/how-to/css-image-modal.html",
        "a-href-tittle": "",
        "how-to-tittle": "",
        "el-Post": "css-image-modal.html",
        "accion": "Ver",
        "postFoto1": "",
        "altPostFoto1": "",
        "postFoto2": "",
        "altPostFoto2": "",
        "postFoto3": "",
        "altPostFoto3": "",
        "postFoto4": "",
        "altPostFoto4": "",
    }, {
        "img-src": "dragvesti.png",
        "fecha-De-Publicacion": "9 julio 2021",
        "a-href": "https://hihello.monster/how-to/css-GalleryResponsive-ImageModal.html",
        "a-href-tittle": "",
        "how-to-tittle": "",
        "el-Post": "css-GalleryResponsive-ImageModal.html",
        "accion": "Ver",
        "postFoto1": "",
        "altPostFoto1": "",
        "postFoto2": "",
        "altPostFoto2": "",
        "postFoto3": "",
        "altPostFoto3": "",
        "postFoto4": "",
        "altPostFoto4": "",
    }, {
        "img-src": "dragvesti.png",
        "fecha-De-Publicacion": "10 julio 2021",
        "a-href": "https://hihello.monster/seccion.rosa",
        "a-href-tittle": "seccion.rosa",
        "how-to-tittle": "seccion.rosa",
        "el-Post": "seccion.rosa",
        "accion": "Ver",
        "postFoto1": "",
        "altPostFoto1": "",
        "postFoto2": "",
        "altPostFoto2": "",
        "postFoto3": "",
        "altPostFoto3": "",
        "postFoto4": "",
        "altPostFoto4": "",
    }, {
        "img-src": "dragvesti.png",
        "fecha-De-Publicacion": "10 julio 2021",
        "a-href": "https://hihello.monster/how-to/css_dropdown_card.html",
        "a-href-tittle": "css_dropdown_card",
        "how-to-tittle": "css_dropdown_card",
        "el-Post": "css_dropdown_card",
        "accion": "Ver",
        "postFoto1": "",
        "altPostFoto1": "",
        "postFoto2": "",
        "altPostFoto2": "",
        "postFoto3": "",
        "altPostFoto3": "",
        "postFoto4": "",
        "altPostFoto4": "",
    }, {
        "img-src": "dragvesti.png",
        "fecha-De-Publicacion": "10 julio 2021",
        "a-href": "https://hihello.monster/how-to/Boton-flotante-draggable-en-JavaScript",
        "a-href-tittle": "Boton-flotante-draggable-en-JavaScript",
        "how-to-tittle": "Boton-flotante-draggable-en-JavaScript",
        "el-Post": "Boton-flotante-draggable-en-JavaScript",
        "accion": "Ver",
        "postFoto1": "",
        "altPostFoto1": "",
        "postFoto2": "",
        "altPostFoto2": "",
        "postFoto3": "",
        "altPostFoto3": "",
        "postFoto4": "",
        "altPostFoto4": "",
    }, {
        "img-src": "dragvesti.png",
        "fecha-De-Publicacion": "10 julio 2021",
        "a-href": "https://hihello.monster/how-to/summary.html",
        "a-href-tittle": "summary",
        "how-to-tittle": "summary",
        "el-Post": "summary",
        "accion": "Ver",
        "postFoto1": "",
        "altPostFoto1": "",
        "postFoto2": "",
        "altPostFoto2": "",
        "postFoto3": "",
        "altPostFoto3": "",
        "postFoto4": "",
        "altPostFoto4": "",
    }, {
        "img-src": "hhm.png",
        "fecha-De-Publicacion": "11 julio 2021",
        "a-href": "https://hihello.monster/raw/true/silverkb.html",
        "a-href-tittle": "Silverkb",
        "how-to-tittle": "Silverkb",
        "el-Post": "Silverkb",
        "accion": "Ver",
        "postFoto1": "",
        "altPostFoto1": "",
        "postFoto2": "",
        "altPostFoto2": "",
        "postFoto3": "",
        "altPostFoto3": "",
        "postFoto4": "",
        "altPostFoto4": "",
        "score-lighthouse": "100 - 100 - 100 - 100",
        "img-score-lighthouse": "https://hihello.monster/raw/true/silverkb.webp",
    }]
};

w3.displayObject("Post", myObject);