var myObject = {
    "proyectos-propios": [{
        "proyecto": "<b>Xiiber Travel</b> Viajes y experiencias para hombres gay ",
        "pageid": "https://luisangelmaciel.github.io/xiiber/",
    }, {
        "proyecto": "<b>Dragvesti</b> La carrera Drag Queen Online y En Vivo",
        "pageid": "https://luisangelmaciel.github.io/dragvesti/",
    }, {
        "proyecto": "<b>How to One</b> Code snippets para HTML, CSS & JavaScript",
        "pageid": "",
    }],
    "proyectos": [{
        "proyecto": "<b>Geus Gourmé</b> Productos gourmet artesanales",
        "pageid": "",
    }, {
        "proyecto": "<b>SiOkey</b> Verificadora de sitios",
        "pageid": "/siokey/index.html",
    }, {
        "proyecto": "<b>Tamales</b> Tamales de Bubulubu, Cremino, Ferrero, entre otros",
        "pageid": "/tamales/",
    }, {
        "proyecto": "<b>Mom´s Pizza</b> Pizzas con extra queso. Especialidad chorihawaian",
        "pageid": "",
    }, {
        "proyecto": "<b>Depravex</b> Sexshop online para hombres gay",
        "pageid": "/depravex/",
    }, {
        "proyecto": "<b></b>",
        "pageid": "/",
    }],
    "one": [{
        "title": "Code snippets para HTML, CSS & JavaScript",
        "pageid": "/templetes/catalogo.html",
    }],
    "Xiiber-travel": [{
        "title": "<b>Tepozspa</b> Spa exclusivo para hombres",
        "pageid": "",
    }],
    "app": [{
        "title": "<b>Frases de Goku</b> Épico random con las frases de Goku de Dragon Ball",
        "pageid": "",
    }],
    "notas": [{
        "proyecto": "Imagen recomendada 749 x 368 px",
    }, {
        "proyecto": "Style Guide. <) eBook | Martech para los nuevos. Explicado con bolitas y palitos ",
    }, {
        "proyecto": "",
    }],
    "hiHelloMaciel": [{
        "img-src": "ico.png",
        "fecha-De-Publicacion": "<time datetime='2021-08-28T20:11:18.929Z'>28 agosto 2021</time>",
        "a-href": "",
        "a-href-tittle": "",
        "how-to-tittle": "",
        "el-Post": "  ",
        "accion": "",
        "postFoto1": "",
        "altPostFoto1": "",
        "postFoto2": " ",
        "altPostFoto2": "",
        "postFoto3": "",
        "altPostFoto3": "",
        "postFoto4": "",
        "altPostFoto4": "",
        "score-lighthouse": "",
        "img-score-lighthouse": "",
    }, {
        "img-src": "ico.png",
        "fecha-De-Publicacion": "<time datetime='2021-08-27T20:11:18.929Z'>27 agosto 2021</time>",
        "a-href": "",
        "a-href-tittle": "",
        "how-to-tittle": "",
        "el-Post": "  ",
        "accion": "",
        "postFoto1": "",
        "altPostFoto1": "",
        "postFoto2": " ",
        "altPostFoto2": "",
        "postFoto3": "",
        "altPostFoto3": "",
        "postFoto4": "",
        "altPostFoto4": "",
        "score-lighthouse": "",
        "img-score-lighthouse": "",
    }, {
        "img-src": "ico.png",
        "fecha-De-Publicacion": "<time datetime='2021-08-26T20:10:18.929Z'>26 agosto 2021</time>",
        "a-href": "https://luisangelmaciel.github.io/one/codigo-alien/",
        "a-href-tittle": "Código [code] alien.",
        "how-to-tittle": "",
        "el-Post": "Aplicación de <blue>'const canvas = document.querySelector' </blue>para generar aleatoriamente simbolos en conjunto con <blue>'window.addEventListener + document.addEventListener' </blue> para cambiar el patrón cada que se toca cualquier parte de la pantalla.",
        "accion": "Ver",
        "postFoto1": "",
        "altPostFoto1": "",
        "postFoto2": " ",
        "altPostFoto2": "",
        "postFoto3": "",
        "altPostFoto3": "",
        "postFoto4": "",
        "altPostFoto4": "",
        "score-lighthouse": "?/100/100/64 a ?/100/100/100",
        "img-score-lighthouse": "https://raw.githubusercontent.com/luisangelmaciel/one/main/codigo-alien/code-alien.webp",
    }, {
        "img-src": "ico.png",
        "fecha-De-Publicacion": "<time datetime='2021-07-02T19:20:18.929Z'>2 julio 2021</time>",
        "a-href": "",
        "a-href-tittle": "",
        "how-to-tittle": "",
        "el-Post": "  No me saluden de lejos, no veo",
        "accion": "",
        "postFoto1": "",
        "altPostFoto1": "",
        "postFoto2": " ",
        "altPostFoto2": "",
        "postFoto3": "",
        "altPostFoto3": "",
        "postFoto4": "",
        "altPostFoto4": "",
        "score-lighthouse": "",
        "img-score-lighthouse": "",
    }, {
        "img-src": "ico.png",
        "fecha-De-Publicacion": "<time datetime='2021-06-26T20:10:18.929Z'>26 junio 2021</time>",
        "a-href": "https://www.youtube.com/watch?v=qHksy0Sa8I0&t=55s",
        "a-href-tittle": "Dalú, la niña de las mil canciones",
        "how-to-tittle": "",
        "el-Post": "Para merecer es necesario trabajar y hacer de ello un hábito.  Dicho por <blue>@Dalú</blue>, la niña de las mil canciones.  ",
        "accion": "Por aquí un concierto en vivo que me gusto mucho.",
        "postFoto1": "",
        "altPostFoto1": "",
        "postFoto2": " ",
        "altPostFoto2": "",
        "postFoto3": "",
        "altPostFoto3": "",
        "postFoto4": "",
        "altPostFoto4": "",
        "score-lighthouse": "",
        "img-score-lighthouse": "",
    }, {
        "img-src": "ico.png",
        "fecha-De-Publicacion": "<time datetime='2021-05-13T20:11:18.929Z'>13 mayo 2021</time>",
        "a-href": "",
        "a-href-tittle": "",
        "how-to-tittle": "",
        "el-Post": " Si tienes poco sexo. La solución está en tus manos ",
        "accion": "",
        "postFoto1": "",
        "altPostFoto1": "",
        "postFoto2": " ",
        "altPostFoto2": "",
        "postFoto3": "",
        "altPostFoto3": "",
        "postFoto4": "",
        "altPostFoto4": "",
        "score-lighthouse": "",
        "img-score-lighthouse": "",
    }, {
        "img-src": "ico.png",
        "fecha-De-Publicacion": "<time datetime='2021-05-13T20:11:18.929Z'>13 abril 2021</time>",
        "a-href": "https://twitter.com/xiibot",
        "a-href-tittle": "Xiibot, el bot de xiiber",
        "how-to-tittle": "",
        "el-Post": " ¿Bots en Twitter? ¿Utilzar uno?. Venga, vámos hacer el experimento.",
        "accion": "Conoce a Xiibot",
        "postFoto1": "",
        "altPostFoto1": "",
        "postFoto2": " ",
        "altPostFoto2": "",
        "postFoto3": "",
        "altPostFoto3": "",
        "postFoto4": "",
        "altPostFoto4": "",
        "score-lighthouse": "",
        "img-score-lighthouse": "",
    }, {
        "img-src": "ico.png",
        "fecha-De-Publicacion": "<time datetime='2021-03-06T20:10:18.929Z'>6 marzo 2021</time>",
        "a-href": "",
        "a-href-tittle": "Tendencia colores 2021",
        "how-to-tittle": "",
        "el-Post": "Gama de azul que nunca pasaran de moda: <span style='color:#017DB0'> #017DB0, </span> <span style='color:#083D77'> #083D77 </span> ",
        "accion": "",
        "postFoto1": "",
        "altPostFoto1": "",
        "postFoto2": " ",
        "altPostFoto2": "",
        "postFoto3": "",
        "altPostFoto3": "",
        "postFoto4": "",
        "altPostFoto4": "",
        "score-lighthouse": "",
        "img-score-lighthouse": "",
    }, ]
};

w3.displayObject("siteMap", myObject);

//   <time datetime='2021-04-29T20:10:18.429Z'>29 April 2021</time>
// <a href = "https://github.com/alfio-event/alf.io" > Gestion de tickets < /a>>   
// Tatoe hi no naka mizu no naka  kusa no naka mori no naka

// Breaking Bad - Walter White Blue Meth